apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.checkcost.triggered"
    tasks:
      - name: "Say Hello World"
        workingDir: "/keptn"
        files:
          - /files/plan.json
        image: "infracost/infracost:ci-0.10.8"
        cmd:
          - "infracost"
        args:
          - 'breakdown'
          - '--path'
          - '/keptn/files/plan.json'
          - '--format'
          - 'table'
          - '--log-level=debug'
        env:
          - name: infracost-details
            valueFrom: secret
