apiVersion: v2
actions:
  - name: "Run infracost"
    events:
      - name: "sh.keptn.event.checkcost.triggered"
    tasks:
      - name: "Execute infracost"
        #workingDir: "/keptn"
        files:
          - /files/plan.json
          - /files/run_infracost_output_to_prom.sh
        image: "alpine:3.15.5" # python base with requests module
        cmd:
          - "/keptn/files/run_infracost_output_to_prom.sh"
        env:
          - name: infracost-details
            valueFrom: secret
